"use strict";
const assert = require('node:assert/strict');
const {renderHTML,toMarkdown}=require('../web/answer_format.js');
const claim={text:'A checked statement.',sources:['S1'],support_status:'automated_supported'};
const result=(...types)=>({claims:types.map(()=>claim),answer_blocks:types.map(type=>({type,claims:[claim]}))});
const paragraph=renderHTML(result('paragraph'));
assert.match(paragraph,/<p class="answer-paragraph">/);assert.doesNotMatch(paragraph,/<li>|<ul>/);
assert.match(paragraph,/data-citation="S1"/);
assert.match(renderHTML(result('bullets')),/<ul class="answer-list"><li>/);
assert.match(renderHTML(result('steps')),/<ol class="answer-list"><li>/);
const mixed=renderHTML(result('paragraph','bullets'));
assert(mixed.indexOf('answer-paragraph')<mixed.indexOf('answer-list'));
assert.equal(toMarkdown(result('paragraph','bullets')),'A checked statement. [S1]\n\n- A checked statement. [S1]');
assert.equal(toMarkdown(result('steps')),'1. A checked statement. [S1]');
assert.equal(renderHTML({claims:[],answer_blocks:[]}), '');
const hostile={text:'<img src=x onerror=alert(1)> **unchecked markup**',sources:['S1" onclick="alert(1)']};
const safe=renderHTML({claims:[hostile],answer_blocks:[{type:'paragraph',claims:[hostile]}]});
assert.doesNotMatch(safe,/<img| onclick="/);assert.match(safe,/&lt;img/);
assert.match(toMarkdown({claims:[hostile]}),/\\<img/);
assert.equal(toMarkdown({claims:[{text:'1. A source label.',sources:['S1']}]}),'1\\. A source label. [S1]');
console.log('Answer rendering: paragraphs, bullets, steps, mixed, citations, empty output, export and escaping passed.');
