'use strict';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const TEAMS={cs:'Customer Success',marketing:'Marketing',bd:'Partners & BD',risk:'Transaction Risk'};
const TYPES={existing:'Existing feature review',change:'Feature change',new_launch:'New feature launch'};
const VIEWS={overview:'Overview',sources:'Sources',brief:'Feature brief',teams:'Team work',actions:'Actions & review',activity:'Activity'};
const STATUS={approved:'Approved',draft:'Ready to review',stale:'Needs an update',changes_requested:'Changes requested',todo:'To do',in_progress:'In progress',done:'Complete',blocked:'Blocked',queued:'Queued',running:'Preparing',completed:'Draft ready',failed:'Failed',superseded:'Inputs changed',interrupted:'Interrupted',recorded:'Review complete',requires_review:'Review reopened'};
let w=null,workspaces=[],view='overview',team='cs',sourceMode='search',riskPanel='rules',mode='ollama',dirty=false,busy=false,polling=false,results=[],query='',confirmation=null,toastTimer=null;
let person={actor:localStorage.getItem('launch-actor')||'Workspace owner',role:'product'};
let health={available:false,model:''};
const allowed=t=>person.role==='product'||person.role===t;
const badge=s=>`<span class="status ${esc(s)}">${esc(STATUS[s]||String(s).replaceAll('_',' '))}</span>`;
const opts=(values,value)=>Object.entries(values).map(([k,v])=>`<option value="${esc(k)}" ${k===value?'selected':''}>${esc(v)}</option>`).join('');
const input=(name,label,value='',required=true,type='text')=>`<label>${esc(label)}<input name="${name}" aria-label="${esc(label)}" value="${esc(value)}" ${required?'required':''} type="${type}"></label>`;
const text=(name,label,value='',rows=3,required=true)=>`<label>${esc(label)}<textarea name="${name}" aria-label="${esc(label)}" rows="${rows}" ${required?'required':''}>${esc(value)}</textarea></label>`;
const select=(name,label,values,value)=>`<label>${esc(label)}<select name="${name}" aria-label="${esc(label)}">${opts(values,value)}</select></label>`;
const date=value=>value?new Date(value).toLocaleString('en-IN',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'';
const sourceLabel=id=>w.sources.find(s=>s.id===id)?.title||'Removed source';
function sourcePreview(id){const source=w.sources.find(s=>s.id===id);return `<details class="source-preview-block"><summary class="micro">Read selected source</summary><blockquote class="source-preview">${esc(source?.text||'Choose a supporting source to inspect its text.')}</blockquote></details>`;}
const heading=(title,description,actions='')=>`<div class="page-head"><div><h1>${esc(title)}</h1><p>${esc(description)}</p></div><div class="actions">${actions}</div></div>`;
const empty=(title,description,action='')=>`<div class="empty"><h2>${esc(title)}</h2><p>${esc(description)}</p>${action}</div>`;
const saveFooter=label=>`<div class="dialog-actions"><button type="button" data-close>Cancel</button><button class="primary" type="submit">${label}</button></div>`;
const scopes=()=>Object.fromEntries(Object.entries({shared:'Feature brief · shared with every team',cs:'Customer Success only',marketing:'Marketing only',bd:'Partners & BD only',risk:'Transaction Risk only'}).filter(([s])=>allowed('product')||s===person.role));
async function api(path,payload){const response=await fetch(path,payload===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw Error(data.error||'The request could not be completed. Try again.');return data;}
function toast(message,error=false){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').className=error?'error':'';$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,error?12000:5000);}
function inlineError(form,message){if(!form){toast(message,true);return;}form.querySelector('.inline-error')?.remove();const node=document.createElement('div');node.className='inline-error';node.setAttribute('role','alert');node.tabIndex=-1;node.textContent=message;if(/(?:workspace|launch) changed/i.test(message)){const recovery=document.createElement('button');recovery.type='button';recovery.className='small';recovery.textContent=form.id==='delete-form'?'Reload delete confirmation':'Refresh workspace';if(form.id==='delete-form')recovery.dataset.reloadDelete=form.dataset.id;else recovery.dataset.refresh='';node.append(document.createElement('br'),recovery);}form.prepend(node);node.focus();node.scrollIntoView({block:'center',behavior:'smooth'});}
async function run(fn,form=null,button=null){if(busy)return;busy=true;const original=button?.textContent;if(button){button.disabled=true;button.textContent='Working…';}try{await fn();}catch(error){inlineError(form,error.message);}finally{busy=false;if(button?.isConnected){button.disabled=false;button.textContent=original;}}}
function confirmAction(title,copy,label='Continue'){return new Promise(resolve=>{confirmation=resolve;$('#confirm-title').textContent=title;$('#confirm-copy').textContent=copy;$('#confirm-button').textContent=label;$('#confirm').showModal();});}
function resolveConfirm(value){$('#confirm').close();const resolve=confirmation;confirmation=null;resolve?.(value);}
async function changeContext(fn){if(dirty&&!await confirmAction('Discard unsaved changes?','Your saved work will stay intact. Changes in the current form will be discarded.','Discard changes'))return;dirty=false;$('#modal').close();await fn();}
function modal(title,body,wide=false){$('#modal-title').textContent=title;$('#modal-body').innerHTML=body;$('#modal').className=wide?'wide':'';$('#modal').showModal();}
function closeModal(){if(dirty){changeContext(()=>render());}else $('#modal').close();}
async function refreshList(){workspaces=await api('/api/launches');}
async function openWorkspace(id){w=await api('/api/launches/'+id);view='overview';team='cs';results=[];query='';dirty=false;render();}
async function home(){w=null;await refreshList();render();}
function navigate(next,which=null){view=next;if(which)team=which;render();$('#content').focus();window.scrollTo(0,0);}
async function mutate(payload,next=null){w=await api(`/api/launches/${w.id}/actions`,{...person,revision:w.revision,...payload});dirty=false;$('#modal').close();$('#updates').hidden=true;if(next)view=next;render();toast('Changes saved.');}
async function queue(kind,which,all=false){
 if(kind==='generate'&&Object.keys(w.artifacts).length&&(!all?w.artifacts[which]:true)){
  if(!await confirmAction('Prepare a new draft?','The previous version stays in Activity. The new draft will need review, and affected completed actions will reopen.','Prepare new draft'))return;
 }
 const route=all?'prepare':'jobs';await api(`/api/launches/${w.id}/${route}`,{...person,revision:w.revision,kind,team:which,mode});
 w=await api('/api/launches/'+w.id);render();toast(all?'All four team drafts are queued.':'Your draft is queued.');
}
function stepButton(){return `<button class="primary" data-next>${esc(w.next_step.label)}</button>`;}
function render(){
 $('#account-button').textContent=person.actor;
 $('#navigation').innerHTML=w?`<div class="nav-caption">Workspace</div>${Object.entries(VIEWS).map(([key,label],i)=>`${key==='activity'?'<div class="nav-divider"></div>':''}<button class="nav-item ${view===key?'active':''}" data-view="${key}" aria-current="${view===key?'page':'false'}"><span class="nav-number">${i>0&&i<5?i:''}</span><span>${label}</span></button>`).join('')}`:'';
 $('#breadcrumbs').innerHTML=w?`<span class="crumb-muted">${esc(w.title)}</span> / ${esc(VIEWS[view])}`:'Workspaces';
 history.replaceState(null,'',w?'#'+w.id+'/'+view:'#workspaces');
 $('#content').innerHTML=w?`${jobStrip()}${({overview,sources,brief,teams,actions,activity}[view])()}`:workspaceHome();
}
function workspaceHome(){return heading('Your workspaces','Review a UPI feature, coordinate a change, or prepare a new launch.',`<button data-create class="primary">New workspace</button>`)+
 (workspaces.length?`<div class="workspace-grid">${workspaces.map(s=>`<article class="card workspace-card"><div class="row"><span class="tag">${esc(TYPES[s.workspace_type])}</span>${s.simulated?'<span class="tag">Example data</span>':''}</div><h2>${esc(s.title)}</h2><p class="micro">${s.approved_teams} of 4 teams reviewed · Updated ${date(s.updated)}</p><p>${badge(s.decision_recorded?'recorded':s.facts_approved?'in_progress':'draft')}</p><div class="actions"><button class="primary" data-open="${s.id}">Open workspace</button><button class="text-button danger" data-delete="${s.id}">Delete</button></div></article>`).join('')}</div>`:empty('Start with a feature','Bring in UPI circulars or your own documents. Then build a reviewed brief and prepare work for the teams involved.','<button class="primary" data-create>Create workspace</button>'))+
 `<div class="notice info section-space"><div><strong>Want to explore the flow first?</strong><p class="micro">Open an existing-feature example with a sample transaction rule. All example records are fictional.</p></div><button data-example>Try the example</button></div>`;
}
function overview(){const done=Object.values(w.artifacts).filter(a=>a.status==='approved').length;return heading(w.title,w.brief,`<button data-settings>Workspace settings</button>`)+
 `<div class="summary-strip"><span>${esc(TYPES[w.workspace_type])}</span>${w.simulated?'<span>Example data</span>':''}<span><strong>${done}/4</strong>teams reviewed</span><span><strong>${w.readiness.completed_tasks}/${w.readiness.total_tasks}</strong>actions complete</span></div>`+
 `<div class="next-step"><div><div class="eyebrow">${w.decision?.status==='recorded'?'Review complete':'Next step'}</div><h2>${esc(w.next_step.label)}</h2><p>${esc(w.next_step.description)}</p></div>${stepButton()}</div>`+
 `<div class="step-track">${[['sources','Sources',`${w.sources.length} documents and excerpts`],['brief','Feature brief',w.facts_approved?'Approved':`${w.facts.length} facts to review`],['teams','Team work',`${done} of 4 teams reviewed`],['actions','Actions & review',`${w.readiness.completed_tasks} actions complete`]].map(([v,title,copy],i)=>`<button class="step-card" data-view="${v}"><span class="step-index">STEP ${i+1}</span><strong>${title}</strong><small>${esc(copy)}</small></button>`).join('')}</div>`+
 `<div class="grid"><div class="card"><h2>Team progress</h2>${Object.entries(TEAMS).map(([key,label])=>`<div class="activity-row row"><span>${label}</span><button class="text-button" data-team="${key}">${w.artifacts[key]?STATUS[w.artifacts[key].status]:'Prepare draft'}</button></div>`).join('')}</div><div class="card"><h2>Latest changes</h2>${w.events.slice(0,4).map(eventRow).join('')}<button class="text-button section-space" data-view="activity">View all activity</button></div></div>`+
 (w.decision?.status==='requires_review'?'<div class="notice"><p>The previous review has reopened because its inputs changed. Follow the next step above to review the affected work.</p></div>':'');
}
function jobStrip(){const pending=w.jobs.filter(j=>['queued','running'].includes(j.state));return pending.length?`<div class="job-strip"><span>${pending.length===1?'Preparing a draft':`${pending.length} drafts in progress`} · You can continue reviewing.</span><button class="text-button" data-view="activity">View progress</button></div>`:'';}
function sources(){return heading('Sources','Choose the circulars and documents that this review should use.',`<button data-view="brief">Continue to feature brief</button>`)+
 `<div class="split"><div class="card"><div class="segmented" aria-label="Source method">${[['search','UPI circulars'],['upload','Upload document'],['paste','Paste text']].map(([id,label])=>`<button data-source-mode="${id}" class="${sourceMode===id?'active':''}">${label}</button>`).join('')}</div>${sourceMode==='search'?`<form id="search-form">${input('query','Search the UPI collection',query||w.title.replace(/(feature )?review/ig,'').trim())}<button class="primary">Find circulars</button><p class="micro">Searches your existing local knowledge base. Review an excerpt before adding it.</p></form><div id="search-results">${searchResults()}</div>`:sourceMode==='upload'?`<div id="upload-area"><label class="upload-drop">Choose a document<input id="upload-file" type="file" accept=".pdf,.docx,.md,.txt"><span>PDF, DOCX, Markdown or text · up to 5 MB</span></label><p class="micro">You will review the extracted text before adding it. Scanned PDFs need OCR first.</p><div id="upload-feedback" role="status"></div></div><div id="upload-preview" hidden></div>`:sourceForm()}</div><div class="card"><h2>In this workspace <span class="tag">${w.sources.length}</span></h2>${w.sources.length?w.sources.map(sourceCard).join(''):empty('No sources yet','Add a circular, upload a file, or paste relevant source text.')}</div></div>`;}
function sourceForm(prefill={}){return `<form data-action="source_add">${input('title','Document title',prefill.title||'')}<div class="fields-two">${select('scope','Use this document for',scopes(),prefill.scope||'shared')}${select('kind','Document type',{internal:'Internal document',public:'Public circular or publication',simulated:'Example data'},prefill.kind||'internal')}</div>${text('text','Text to use',prefill.text||'',9)}<p class="micro">Keep only the relevant content · maximum 24,000 characters per source.</p><button class="primary">Add to workspace</button></form>`;}
function sourceCard(s){const url=s.provenance?.source_url;return `<div class="source-item"><details><summary>${esc(s.title)}</summary><p class="micro">${esc(s.scope==='shared'?'Shared feature evidence':TEAMS[s.scope])}${s.provenance?.page?' · Page '+esc(s.provenance.page):''}</p><div class="prose">${esc(s.text)}</div>${url&&/^https?:\/\//i.test(url)?`<p><a href="${esc(url)}" target="_blank" rel="noopener">Original circular ↗</a></p>`:''}${allowed(s.scope==='shared'?'product':s.scope)?`<button class="text-button danger" data-remove-source="${s.id}">Remove source</button>`:''}</details></div>`;}
function searchResults(){return results.map((p,n)=>{const added=w.sources.some(s=>s.provenance?.chunk_id===p.id);return `<article class="source-result"><h3>${esc(p.title)}</h3><p class="micro">${esc(p.document_id)} · Page ${esc(p.page)}${p.issue_date?' · '+esc(p.issue_date):''}</p><details><summary>Read excerpt</summary><p class="prose">${esc(p.text)}</p></details><button class="small" data-import="${n}" ${added||!allowed('product')?'disabled':''}>${added?'Added to workspace':'Add to workspace'}</button></article>`}).join('');}
function brief(){const shared=w.sources.some(s=>s.scope==='shared');return heading('Feature brief','Agree on the facts before asking teams to prepare their work.',allowed('product')?'<button data-add-fact>Add a fact</button>':'')+(!allowed('product')&&!w.facts_approved?'<div class="notice info"><p>The product owner needs to approve this brief.</p><button data-account>Change review role</button></div>':'')+
 (!shared?empty('Add evidence first','The brief needs a circular excerpt or a shared document.','<button class="primary" data-view="sources">Add sources</button>'):
 `<div class="row section-space"><span>${w.facts.length} facts ${w.facts_approved?'· Approved':''}</span>${allowed('product')?`<button data-extract>${w.facts.length?'Find more facts with AI':'Draft brief with AI'}</button>`:''}</div>${w.questions.length?`<div class="notice notice-stack"><h3>Questions to resolve</h3><ul class="question-list">${w.questions.map(q=>`<li>${esc(q)}</li>`).join('')}</ul>${allowed('product')?'<button data-resolve>Record answers or decisions</button>':''}</div>`:''}`+
 (w.facts.length?`<div class="card section-space">${w.facts.map(f=>`<article class="fact-row"><div class="row"><h3>${esc(f.label)}</h3>${allowed('product')?`<button class="text-button" data-edit-fact="${f.id}">Edit</button>`:''}</div><p>${esc(f.value)}</p><details><summary class="micro">Source: ${esc(sourceLabel(f.source_id))}</summary><blockquote>${esc(f.quote)}</blockquote></details></article>`).join('')}</div>`:empty('Prepare a first draft','Use local AI to extract cited facts, or add a fact manually.'))+
 (w.facts.length&&allowed('product')?`<div class="card review-box"><div class="row"><h2>${w.facts_approved?'Feature brief approved':'Review the brief'}</h2>${badge(w.facts_approved?'approved':'draft')}</div>${w.facts_approved?`<p class="micro">${esc(w.fact_approval.actor)} · ${date(w.fact_approval.time)}</p><button class="primary" data-view="teams">Continue to team work</button>`:w.questions.length?'<p>Resolve the questions above before approving this brief.</p><button data-resolve>Resolve questions</button>':`<form data-action="facts_approve" data-next="teams">${text('note','Review note','',2)}<button class="primary">Approve brief & continue</button></form>`}</div>`:''));}
function modeControl(){return `<select class="mode-picker" id="draft-mode" aria-label="Drafting method">${opts({ollama:'Local AI',template:'Example templates'},mode)}</select>`;}
function teams(){const a=w.artifacts[team];return heading('Team work','Prepare and review each team’s response to the feature brief.',allowed('product')&&w.facts_approved?`<button data-prepare-all class="primary">Prepare all team drafts</button>`:'')+
 `<div class="team-switcher">${Object.entries(TEAMS).map(([key,label])=>`<button data-team="${key}" class="${key===team?'active':''}"><strong>${label}</strong>${w.artifacts[key]?badge(w.artifacts[key].status):'<span class="tag">Not prepared</span>'}</button>`).join('')}</div>`+
 (!w.facts_approved?'<div class="notice"><p>Review and approve the feature brief before preparing team drafts.</p><button data-view="brief">Review feature brief</button></div>':'')+
 `<div class="team-toolbar"><div><h2>${TEAMS[team]}</h2>${team==='risk'?'<span class="micro">Transaction rules, their applicability and proposed changes.</span>':''}</div><div class="actions">${modeControl()}${allowed(team)?`<button data-generate class="primary" ${!w.facts_approved?'disabled':''}>${a?'Prepare new draft':'Prepare draft'}</button>`:''}${team==='bd'&&allowed('bd')?'<button data-partners>Partner register</button>':''}</div></div>`+
 (team==='risk'?`<div class="segmented"><button data-risk-panel="rules" class="${riskPanel==='rules'?'active':''}">Transaction rules (${w.risk_rules.length})</button><button data-risk-panel="draft" class="${riskPanel==='draft'?'active':''}">Assessment ${a?'':'· not prepared'}</button></div>`:'')+
 (team==='risk'&&riskPanel==='rules'?rulesView():draftView(a));}
function rulesView(){return `<div class="row section-space"><p class="muted">Record the rules supplied by the UPI transaction-risk team.</p>${allowed('risk')?'<button data-add-rule class="primary">Add transaction rule</button>':''}</div>${w.risk_rules.length?w.risk_rules.map(r=>`<article class="card rule-card"><div class="row"><h3>${esc(r.name)}</h3><div class="actions"><span class="tag">${esc(r.status)}${r.status==='active'?' · reported':''}</span>${allowed('risk')?`<button class="small" data-edit-rule="${r.id}">Edit rule</button>`:''}</div></div><p class="micro">${esc(r.feature_scope)}</p><div class="rule-condition"><strong>When</strong> ${esc(r.condition)}<br><strong>Action</strong> ${esc(r.response.replaceAll('_',' '))}</div><details><summary class="micro">Owner and evidence</summary><p>${esc(r.owner)} · ${esc(r.verification||'Verification evidence not supplied')}</p>${r.quote?`<blockquote>${esc(r.quote)}</blockquote><p class="micro">${esc(sourceLabel(r.source_id))}</p>`:'<p class="micro">No source evidence attached.</p>'}</details></article>`).join(''):empty('No transaction rules supplied','Circulars describe requirements; they do not show which internal rules are active. Add your rule evidence in Sources, then record the relevant rules here.','<button data-view="sources">Add internal evidence</button>')}<p class="footer-note">Rules are assessed here, not executed or deployed. “Active” is a reported status supported by your internal evidence.</p>`;}
function draftView(a){if(!a)return empty('No draft yet','Prepare a draft from the approved brief, then review it with the team.');const flagged=w.issues.filter(i=>i.team===team);return `<div class="row"><span>${badge(a.status)} <span class="micro">Version ${a.version} · ${a.generator==='template'?'Example template':'Local AI draft'}</span></span>${allowed(team)&&a.status!=='stale'?'<button data-edit-draft>Edit draft</button>':''}</div>`+
 (a.status==='stale'?`<div class="notice"><p>${esc(a.stale_reason||'The inputs have changed.')} Prepare a new draft before reviewing it.</p>${!w.facts_approved?'<button data-view="brief">Review brief</button>':'<button data-generate>Prepare new draft</button>'}</div>`:'')+
 (team==='risk'&&a.rule_assessments?.length?`<div class="card section-space"><h2>Rule-by-rule assessment</h2>${a.rule_assessments.map(r=>`<div class="finding"><h3>${esc(w.risk_rules.find(x=>x.id===r.rule_id)?.name||'Removed rule')}</h3><span class="tag">${esc(r.applicability.replaceAll('_',' '))}</span> <span class="tag">${esc(r.recommendation.replaceAll('_',' '))}</span><p>${esc(r.rationale)}</p>${r.proposed_change?`<p><strong>Suggested action:</strong> ${esc(r.proposed_change)}</p>`:''}</div>`).join('')}</div>`:'')+
 `<div class="card section-space">${a.items.map(i=>`<article class="draft-item"><span class="tag">${{source_summary:'From the evidence',proposal:'Recommendation',open_question:'Open question'}[i.kind]}</span><h3>${esc(i.title)}</h3><p>${esc(i.body)}</p>${i.fact_ids.length||i.source_refs.length?`<details><summary class="micro">Supporting evidence</summary>${i.fact_ids.map(id=>{const f=w.facts.find(x=>x.id===id);return f?`<p class="micro"><strong>${esc(f.label)}</strong> · ${esc(f.value)}</p>`:'<p class="micro">The referenced fact was removed.</p>'}).join('')}${i.source_refs.map(r=>`<blockquote>${esc(r.quote)}<br><small>${esc(sourceLabel(r.source_id))}</small></blockquote>`).join('')}</details>`:''}</article>`).join('')}</div>`+
 (a.open_questions.length?`<div class="notice notice-stack"><h3>Questions for this team</h3><ul>${a.open_questions.map(q=>`<li>${esc(q)}</li>`).join('')}</ul><button data-edit-draft>Resolve questions in the draft</button></div>`:'')+
 (a.review?`<p class="micro section-space">Reviewed by ${esc(a.review.actor)} · ${date(a.review.time)}<br>${esc(a.review.note)}</p>`:'')+
 (allowed(team)&&a.status!=='stale'?`<div class="card review-box"><h2>${a.status==='approved'?'Team review recorded':'Review this draft'}</h2>${flagged.length?`<p>${esc(flagged[0].message)}</p><button data-edit-draft>Update draft</button>`:a.status==='approved'?'<button data-view="actions">Continue to actions & review</button>':`<form data-action="artifact_review" data-team="${team}">${select('decision','Decision',{approved:'Approve this draft',changes_requested:'Request changes'},'approved')}${text('note','Review note','',2)}<button class="primary">Record team review</button></form>`}</div>`:'');}
function actions(){return heading('Actions & review','Record who owns each action, what was done and the evidence behind it.',allowed(team)?'<button data-add-task>Add action</button>':'')+
 `<div class="card table-card"><div class="table-wrap"><table><thead><tr><th>Action</th><th>Owner / due date</th><th>Status</th><th></th></tr></thead><tbody>${w.tasks.map(t=>`<tr><td><strong>${esc(t.title)}</strong><div class="micro">${TEAMS[t.team]}${t.depends_on.length?' · After '+t.depends_on.map(id=>esc(w.tasks.find(x=>x.id===id)?.title)).join(', '):''}</div>${t.reopened_reason?`<div class="micro">Reopened: ${esc(t.reopened_reason)}</div>`:''}</td><td>${esc(t.owner||'Unassigned')}<div class="micro">${esc(t.due||'No due date')}</div></td><td>${badge(t.status)}</td><td>${allowed(t.team)?`<button class="small" data-edit-task="${t.id}">Update</button>`:''}</td></tr>`).join('')}</tbody></table></div></div>`+
 `<div class="card section-space"><div class="row"><h2>${w.workspace_type==='new_launch'?'Launch decision':'Complete the workspace review'}</h2>${w.decision?badge(w.decision.status):''}</div>${w.readiness.ready?(w.decision?.status==='recorded'?`<p>Review recorded by ${esc(w.decision.actor)} on ${date(w.decision.time)}.</p><p>${esc(w.decision.note)}</p><button class="primary" data-export>Export review pack</button>`:allowed('product')?`<p class="muted">The brief and all team drafts are approved. Required actions are complete.</p><form data-action="launch_decide">${text('note','Decision and rationale','',3)}<button class="primary">${w.workspace_type==='new_launch'?'Record launch decision':'Complete review'}</button></form>`:'<p>The product owner can now record the final review.</p><button data-account>Change review role</button>'):`<p class="muted">A few items still need attention. Continue with the next required step.</p><div class="actions">${stepButton()}</div><details><summary class="micro">View remaining items (${w.readiness.blockers.length})</summary><ul>${w.readiness.blockers.map(b=>`<li>${esc(b)}</li>`).join('')}</ul></details>`}</div>`;}
const EVENT_NAMES={create:'Workspace created',source_add:'Source added',source_remove:'Source removed',fact_save:'Feature brief updated',fact_remove:'Fact removed',facts_approve:'Feature brief approved',questions_resolve:'Questions resolved',partner_save:'Partner details updated',control_save:'Legacy control updated',risk_rule_save:'Transaction rule updated',risk_rule_remove:'Transaction rule removed',artifact_save:'Team draft edited',artifact_review:'Team review recorded',task_save:'Action updated',launch_decide:'Final review recorded',brief_save:'Workspace details updated',extract_completed:'Feature facts prepared',generate_completed:'Team draft prepared'};
function eventRow(e){return `<div class="activity-row"><div class="row"><strong>${esc(EVENT_NAMES[e.action]||e.action.replaceAll('_',' '))}</strong><time>${date(e.created)}</time></div><span class="micro">${esc(e.actor)}${e.detail.team?' · '+TEAMS[e.detail.team]:''}</span></div>`;}
function activity(){return heading('Activity','Review changes, earlier drafts and drafting progress.','<button class="primary" data-export>Export review pack</button>')+
 `<div class="grid"><div class="card"><h2>Recent changes</h2>${w.events.map(eventRow).join('')}</div><div><div class="card"><h2>Drafting progress</h2>${w.jobs.length?w.jobs.map(j=>`<div class="activity-row"><div class="row"><strong>${j.kind==='extract'?'Feature brief':TEAMS[j.team]}</strong>${badge(j.state)}</div>${j.error?`<p class="micro">${esc(j.error)}</p>`:`<p class="micro">${date(j.updated)}</p>`}${['failed','interrupted','superseded'].includes(j.state)?`<button class="small" data-retry="${j.id}">Try again</button>`:''}</div>`).join(''):'<p class="muted">Drafting progress will appear here.</p>'}</div><div class="card"><h2>Earlier drafts</h2>${w.archive.length?[...w.archive].reverse().map(a=>`<details><summary>${TEAMS[a.team]} · version ${a.version}</summary>${a.items.map(i=>`<h3>${esc(i.title)}</h3><p class="prose">${esc(i.body)}</p>`).join('')}</details>`).join(''):'<p class="muted">Previous versions are kept when a draft is edited or regenerated.</p>'}</div></div></div>`;}

function createForm(){modal('New workspace',`<form id="create-form"><p class="muted">What would you like to work on?</p><div class="type-options">${[['existing','Existing feature review','Understand impact, update guidance or assess transaction rules.'],['change','Feature change','Coordinate a circular update or a change in requirements.'],['new_launch','New feature launch','Prepare teams and record launch readiness.']].map(([id,label,copy])=>`<label class="type-option"><input type="radio" name="workspace_type" value="${id}" ${id==='existing'?'checked':''}><span><strong>${label}</strong><small>${copy}</small></span></label>`).join('')}</div>${input('title','Workspace name')}${text('brief','What do you want to achieve?','',3)}<label class="check"><input type="checkbox" name="simulated"> This workspace uses example data</label>${saveFooter('Create workspace')}</form>`);}
async function deleteForm(id){modal('Delete workspace','<p class="loading">Loading the current workspace…</p>');const target=await api('/api/launches/'+id);modal('Delete workspace',`<form id="delete-form" data-id="${target.id}" data-revision="${target.revision}"><p>This permanently deletes <strong>${esc(target.title)}</strong>, its sources, drafts, reviews and queued work. Your circular knowledge base stays intact.</p>${input('confirmation','Type the workspace name to confirm')}<p class="micro">${esc(target.title)}</p><div class="dialog-actions"><button type="button" data-close>Cancel</button><button type="submit" class="danger">Delete workspace permanently</button></div></form>`);}
function factForm(id){const f=w.facts.find(x=>x.id===id)||{};if(!w.sources.some(s=>s.scope==='shared')){navigate('sources');toast('Add a shared source before adding a fact.');return;}modal(f.id?'Edit feature fact':'Add feature fact',`<form data-action="fact_save" data-id="${esc(f.id||'')}">${input('label','Fact title',f.label)}${text('value','Fact',f.value)}${select('source_id','Supporting source',Object.fromEntries(w.sources.filter(s=>s.scope==='shared').map(s=>[s.id,s.title])),f.source_id)}${sourcePreview(f.source_id||w.sources.find(s=>s.scope==='shared')?.id)}${text('quote','Exact quotation from the source',f.quote,4)}${f.id?`<button type="button" class="text-button danger" data-remove-fact="${f.id}">Remove this fact</button>`:''}${saveFooter('Save fact')}</form>`);}
function ruleForm(id){const r=w.risk_rules.find(x=>x.id===id)||{};modal(r.id?'Edit transaction rule':'Add transaction rule',`<form data-action="risk_rule_save" data-id="${esc(r.id||'')}">${input('name','Rule name',r.name)}${text('feature_scope','Applies to',r.feature_scope,2)}${text('condition','Transaction condition',r.condition,3)}<div class="fields-two">${select('response','Rule action',{monitor:'Monitor',decline:'Decline',step_up:'Step-up verification',review:'Send for review',rate_limit:'Rate limit'},r.response||'monitor')}${select('status','Reported status',{proposed:'Proposed',documented:'Documented',active:'Active',retired:'Retired'},r.status||'proposed')}</div>${input('owner','Rule owner',r.owner)}${select('source_id','Supporting rule evidence',{'':'No evidence attached',...Object.fromEntries(w.sources.filter(s=>['shared','risk'].includes(s.scope)).map(s=>[s.id,s.title]))},r.source_id||'')}${sourcePreview(r.source_id)}${text('quote','Exact quotation supporting this rule',r.quote,3,false)}${text('verification','Configuration, deployment or test evidence',r.verification,2,false)}<p class="micro">Documented, active and retired rules need a supporting source. Active status requires internal evidence and a configuration/deployment note.</p>${!w.sources.some(s=>['shared','risk'].includes(s.scope))?'<p class="micro">Add internal rule evidence through Sources before recording an existing rule.</p>':''}${r.id?`<button type="button" class="text-button danger" data-remove-rule="${r.id}">Remove rule</button>`:''}${saveFooter('Save transaction rule')}</form>`,true);}
function taskForm(id){const t=w.tasks.find(x=>x.id===id)||{};modal(t.id?'Update action':'Add action',`<form data-action="task_save" data-id="${esc(t.id||'')}">${input('title','Action',t.title)}${!t.id?select('team','Team',Object.fromEntries(Object.entries(TEAMS).filter(([key])=>allowed(key))),team):`<input type="hidden" name="team" value="${t.team}">`}<div class="fields-two">${input('owner','Owner',t.owner,false)}${select('status','Status',{todo:'To do',in_progress:'In progress',blocked:'Blocked',done:'Complete'},t.status||'todo')}</div>${input('due','Due date',t.due,false,'date')}${text('evidence','Completion evidence or blocker details',t.evidence,3,false)}<label>Prerequisites<select name="depends_on" aria-label="Prerequisites" multiple size="4">${w.tasks.filter(x=>x.id!==t.id).map(x=>`<option value="${x.id}" ${(t.depends_on||[]).includes(x.id)?'selected':''}>${esc(x.title)}</option>`).join('')}</select></label><p class="micro">Completion requires an owner, evidence, current team approval and completed prerequisites. Hold Ctrl or Cmd to select multiple prerequisites.</p>${saveFooter('Save action')}</form>`);}
function draftForm(){const a=w.artifacts[team];modal('Edit '+TEAMS[team]+' draft',`<form data-action="artifact_save" data-team="${team}">${a.items.map((i,n)=>`<fieldset class="card section-space"><legend>Section ${n+1}</legend>${input('title_'+n,'Title',i.title)}${text('body_'+n,'Content',i.body,5)}${select('kind_'+n,'Content type',{source_summary:'From the evidence',proposal:'Recommendation',open_question:'Open question'},i.kind)}<label>Supporting facts<select name="refs_${n}" multiple aria-label="Supporting facts for section ${n+1}" size="3">${w.facts.map(f=>`<option value="${f.id}" ${i.fact_ids.includes(f.id)?'selected':''}>${esc(f.label)}</option>`).join('')}</select></label></fieldset>`).join('')}${(a.rule_assessments||[]).map((r,n)=>`<fieldset class="card section-space"><legend>${esc(w.risk_rules.find(x=>x.id===r.rule_id)?.name||'Rule')}</legend>${select('applicability_'+n,'Applicability',{relevant:'Relevant',possibly_relevant:'Possibly relevant',not_relevant:'Not relevant'},r.applicability)}${select('recommendation_'+n,'Recommendation',{retain:'Retain',review:'Review',tune:'Tune',retire:'Retire',needs_evidence:'Needs evidence'},r.recommendation)}${text('rationale_'+n,'Rationale',r.rationale)}${text('proposed_change_'+n,'Proposed change',r.proposed_change,2,false)}</fieldset>`).join('')}${text('open_questions','Unresolved questions · one per line',a.open_questions.join('\n'),3,false)}${text('note','What changed / how questions were resolved','',2)}${saveFooter('Save draft revision')}</form>`,true);}
function partners(){modal('Partner register',`<div>${w.partners.map(p=>`<div class="activity-row"><div class="row"><h3>${esc(p.name)}</h3><button class="small" data-edit-partner="${p.id}">Edit</button></div><p class="micro">${esc(p.stage)} · ${esc(p.capabilities)}</p></div>`).join('')||'<p class="muted">No partner details added yet.</p>'}<button data-add-partner class="primary section-space">Add partner</button></div>`);}
function partnerForm(id){const p=w.partners.find(x=>x.id===id)||{};modal(p.id?'Edit partner':'Add partner',`<form data-action="partner_save" data-id="${esc(p.id||'')}">${input('name','Partner name',p.name)}${text('capabilities','Relevant capabilities and context',p.capabilities)}${select('stage','Recorded stage',{candidate:'Candidate',interested:'Interested',testing:'Testing',ready:'Ready',live:'Live'},p.stage||'candidate')}${text('evidence','Supporting evidence',p.evidence,2,false)}${saveFooter('Save partner')}</form>`);}
function settings(){modal('Workspace settings',`<form data-action="brief_save">${input('title','Workspace name',w.title)}${select('workspace_type','Workspace type',TYPES,w.workspace_type)}${text('brief','Objective',w.brief,4)}<p class="micro">Changing the objective or type reopens the brief and affected team reviews.</p>${saveFooter('Save settings')}</form>${allowed('product')?`<div class="danger-zone"><h3>Delete workspace</h3><p class="micro">Permanently remove this workspace and its review history.</p><button class="danger" data-delete="${w.id}">Delete workspace</button></div>`:''}`);}
function account(){modal('Reviewer',`<form id="account-form">${input('actor','Your name',person.actor)}${select('role','Working as',{product:'Product owner',...TEAMS},person.role)}<p class="micro">Roles organise review responsibilities in this local app. They are not separate authenticated accounts.</p>${saveFooter('Save reviewer')}</form>`);}
function help(){modal('How this workspace works',`<ol><li><strong>Sources:</strong> select UPI circulars or upload your documents.</li><li><strong>Feature brief:</strong> check the facts and approve the shared understanding.</li><li><strong>Team work:</strong> prepare drafts and review each team’s response.</li><li><strong>Actions & review:</strong> record completion evidence and the final decision.</li></ol><h3 class="section-space">Local drafting</h3><p>${health.available?'Your local AI model is available.':'Start Ollama to use AI drafting, then refresh the connection below.'} Choose “Example templates” for a deterministic demonstration.</p><p class="micro">${esc(health.model)} · Documents stay in this local application. No emails, publications or transaction-rule deployments are performed.</p><button data-health>Refresh AI connection</button><h3 class="section-space">Transaction Risk</h3><p>Supply the relevant internal rules and evidence. The application assesses conditions, actions and applicability. It cannot discover live UPI rule configurations from public circulars.</p><p class="micro">This is a course prototype, not an NPCI production system. Uploaded PDF text and model drafts still need review.</p>`);}
async function healthCheck(){health=await api('/api/health');$('#model-status').textContent=health.available?'Local AI connected':'Local AI offline';$('#model-status').className='connection'+(health.available?' ready':'');}
async function exportPack(){const response=await fetch(`/api/launches/${w.id}/export`);if(!response.ok)throw Error('Could not export this review. Refresh and try again.');const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=w.title.replace(/[^a-z0-9 -]/ig,'').trim()+'-review.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

document.addEventListener('click',event=>{
 const b=event.target.closest('button');if(!b||b.disabled||(b.form&&b.type==='submit'))return;
 if(b.id==='confirm-button'){resolveConfirm(true);return;}if(b.hasAttribute('data-cancel')){resolveConfirm(false);return;}
 if(b.hasAttribute('data-close')){closeModal();return;}
 run(async()=>{
  if(b.hasAttribute('data-home'))return changeContext(home);
  if(b.dataset.open)return changeContext(()=>openWorkspace(b.dataset.open));
  if(b.dataset.view)return changeContext(()=>navigate(b.dataset.view));
  if(b.hasAttribute('data-next'))return changeContext(()=>{navigate(w.next_step.view,w.next_step.team);if(w.next_step.task_id)taskForm(w.next_step.task_id);});
  if(b.hasAttribute('data-refresh'))return changeContext(async()=>{w=await api('/api/launches/'+w.id);$('#updates').hidden=true;render();});
  if(b.hasAttribute('data-create'))return changeContext(()=>{if(!allowed('product')){account();toast('Choose Product owner to create a workspace.');}else createForm();});
  if(b.hasAttribute('data-example'))return changeContext(async()=>{w=await api('/api/demo',person);view='overview';render();toast('Example workspace created.');});
  if(b.dataset.reloadDelete){dirty=false;return deleteForm(b.dataset.reloadDelete);}
  if(b.dataset.delete)return changeContext(()=>deleteForm(b.dataset.delete));
  if(b.hasAttribute('data-settings'))return changeContext(settings);
  if(b.hasAttribute('data-account'))return changeContext(account);
  if(b.hasAttribute('data-help'))return changeContext(help);
  if(b.hasAttribute('data-health')){await healthCheck();help();return;}
  if(b.dataset.sourceMode)return changeContext(()=>{sourceMode=b.dataset.sourceMode;render();});
  if(b.dataset.import!==undefined){const p=results[Number(b.dataset.import)];w=await api(`/api/launches/${w.id}/evidence`,{...person,revision:w.revision,chunk_id:p.id});render();toast('Circular excerpt added.');return;}
  if(b.dataset.removeSource){if(await confirmAction('Remove this source?','Facts derived from this source will be removed. Linked rules will return to proposed status, and affected reviews will reopen.','Remove source'))await mutate({action:'source_remove',id:b.dataset.removeSource});return;}
  if(b.hasAttribute('data-add-fact'))return changeContext(()=>factForm());
  if(b.dataset.editFact)return changeContext(()=>factForm(b.dataset.editFact));
  if(b.dataset.removeFact){if(await confirmAction('Remove this fact?','Affected team reviews and completed actions will reopen.','Remove fact'))await mutate({action:'fact_remove',id:b.dataset.removeFact});return;}
  if(b.hasAttribute('data-extract')){if(!health.available)throw Error('Start Ollama to prepare a brief with AI. You can also use “Add a fact” on this page.');mode='ollama';return queue('extract',null);}
  if(b.hasAttribute('data-resolve'))return changeContext(()=>modal('Resolve brief questions',`<form data-action="questions_resolve"><ul class="question-list">${w.questions.map(q=>`<li>${esc(q)}</li>`).join('')}</ul>${text('note','Answers, decisions and supporting evidence','',5)}${saveFooter('Record decisions')}</form>`));
  if(b.dataset.team)return changeContext(()=>{team=b.dataset.team;view='teams';riskPanel=w.artifacts.risk?'draft':'rules';render();});
  if(b.dataset.riskPanel)return changeContext(()=>{riskPanel=b.dataset.riskPanel;render();});
  if(b.hasAttribute('data-prepare-all')||b.hasAttribute('data-generate')){if(mode==='ollama'&&!health.available)throw Error('Start Ollama or select “Example templates” in the drafting menu on this page.');return queue('generate',team,b.hasAttribute('data-prepare-all'));}
  if(b.hasAttribute('data-add-rule'))return changeContext(()=>ruleForm());
  if(b.dataset.editRule)return changeContext(()=>ruleForm(b.dataset.editRule));
  if(b.dataset.removeRule){if(await confirmAction('Remove transaction rule?','The risk assessment will need an update. This does not change any live transaction system.','Remove rule'))await mutate({action:'risk_rule_remove',id:b.dataset.removeRule});return;}
  if(b.hasAttribute('data-edit-draft'))return changeContext(draftForm);
  if(b.hasAttribute('data-partners'))return changeContext(partners);
  if(b.hasAttribute('data-add-partner'))return changeContext(()=>partnerForm());
  if(b.dataset.editPartner)return changeContext(()=>partnerForm(b.dataset.editPartner));
  if(b.hasAttribute('data-add-task'))return changeContext(()=>taskForm());
  if(b.dataset.editTask)return changeContext(()=>taskForm(b.dataset.editTask));
  if(b.hasAttribute('data-export'))return exportPack();
  if(b.dataset.retry){const j=w.jobs.find(j=>j.id===b.dataset.retry);if(j.kind==='generate'&&!w.facts_approved){navigate('brief');toast('Approve the current feature brief before retrying.');return;}mode=j.mode||mode;return queue(j.kind,j.team);}
 });
});
document.addEventListener('submit',event=>{
 event.preventDefault();const f=event.target,fd=new FormData(f),data=Object.fromEntries(fd);
 run(async()=>{
  if(f.id==='create-form'){w=await api('/api/launches',{...person,...data,simulated:data.simulated==='on'});dirty=false;$('#modal').close();view='sources';render();return;}
  if(f.id==='delete-form'){await api(`/api/launches/${f.dataset.id}/delete`,{...person,revision:Number(f.dataset.revision),confirmation:data.confirmation});dirty=false;$('#modal').close();await home();toast('Workspace deleted.');return;}
  if(f.id==='account-form'){person={actor:data.actor.trim(),role:data.role};localStorage.setItem('launch-actor',person.actor);dirty=false;$('#modal').close();render();return;}
  if(f.id==='search-form'){query=data.query;$('#search-results').innerHTML='<p class="loading">Searching your UPI collection…</p>';results=await api('/api/evidence?q='+encodeURIComponent(query));$('#search-results').innerHTML=results.length?searchResults():'<p class="micro">No matching passages. Try a feature name or circular number.</p>';return;}
  if(!f.dataset.action)return;
  const payload={...data,action:f.dataset.action};if(f.dataset.id)payload.id=f.dataset.id;if(f.dataset.team)payload.team=f.dataset.team;
  if(payload.action==='source_add'&&data.text.length>24000)throw Error('This source is longer than 24,000 characters. Keep the relevant excerpt in “Text to use” below.');
  if(payload.action==='task_save')payload.depends_on=fd.getAll('depends_on');
  if(payload.action==='artifact_save'){
   const a=w.artifacts[team];payload.items=a.items.map((i,n)=>({...i,title:data['title_'+n],body:data['body_'+n],kind:data['kind_'+n],fact_ids:fd.getAll('refs_'+n)}));
   payload.open_questions=data.open_questions.split('\n').map(s=>s.trim()).filter(Boolean);
   payload.rule_assessments=(a.rule_assessments||[]).map((r,n)=>({...r,applicability:data['applicability_'+n],recommendation:data['recommendation_'+n],rationale:data['rationale_'+n],proposed_change:data['proposed_change_'+n]}));
  }
  await mutate(payload,f.dataset.next||null);
 },f,event.submitter);
});
document.addEventListener('input',event=>{if(event.target.closest('form:not(#search-form)'))dirty=true;});
document.addEventListener('change',event=>{
 if(event.target.name==='source_id'&&event.target.closest('#modal')){const preview=$('#modal .source-preview-block');if(preview)preview.outerHTML=sourcePreview(event.target.value);return;}
 if(event.target.id==='draft-mode'){mode=event.target.value;return;}
 if(event.target.id!=='upload-file')return;
 const file=event.target.files[0];if(!file)return;
 run(async()=>{
  if(file.size>5*1024*1024)throw Error('Choose a document smaller than 5 MB.');
  $('#upload-feedback').textContent='Reading your document…';
  const encoded=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=()=>reject(Error('The selected file could not be read.'));reader.readAsDataURL(file);});
  const result=await api('/api/extract-document',{name:file.name,data:encoded});
  $('#upload-feedback').textContent=result.truncated?'The first 24,000 characters are shown. Select the relevant text before adding this source.':result.note||'Review the text below before adding it.';
  $('#upload-preview').innerHTML=sourceForm({title:result.name,text:result.text});$('#upload-preview').hidden=false;dirty=true;
 },$('#upload-area'));
});
$('#confirm').addEventListener('cancel',event=>{event.preventDefault();resolveConfirm(false);});
$('#modal').addEventListener('cancel',event=>{event.preventDefault();closeModal();});
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
async function poll(){if(!w||busy||polling||document.hidden)return;polling=true;const id=w.id;try{const next=await api('/api/launches/'+id);if(busy||!w||w.id!==id||next.revision<w.revision)return;if(dirty||$('#modal').open){if(next.revision!==w.revision)$('#updates').hidden=false;return;}if(next.revision!==w.revision||JSON.stringify(next.jobs)!==JSON.stringify(w.jobs)){w=next;render();}}catch(error){if(error.message==='Launch not found'){$('#modal').close();dirty=false;$('#updates').hidden=true;w=null;await refreshList();render();toast('This workspace was deleted in another window.');}else toast('Connection lost. Check that the local workspace server is running.',true);}finally{polling=false;}}
(async()=>{try{await refreshList();const parts=location.hash.slice(1).split('/');if(parts[0]&&workspaces.some(s=>s.id===parts[0])){await openWorkspace(parts[0]);if(VIEWS[parts[1]]){view=parts[1];render();}}else render();await healthCheck();}catch(error){toast(error.message,true);}setInterval(poll,3000);})();
